# ============================================================
# build_tcl.tcl — Automated Gowin Build Script
# ============================================================
# 1. Creates a project
# 2. Add files and top module
# 3. Creates and generates an IP
# 4. Runs synthesis and place & route
# ============================================================
# https:/sahasmunamala.substack.com/p/automating-fpga-workflows-for-source-control?r=6ohy3k
# ============================================================

# --- USER PARAMETERS ----------------------------------------
set prj_name "CoralNPU_console60k"
set prj_dir  "C:/Workspace/FPGA/coralnpu-nano20k/fpga/console60k "
set top_name  "chip_console60k_CoreMini "
set device  "XXXXXXXXXXXXXXXXXXXXXx "
set device_version  "C "

# --- CREATE PROJECT -----------------------------------------
create_project -name $prj_name -dir $prj_dir -pn $device -device_version $device_version -force

# --- ADD DESIGN SOURCE --------------------------------------
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/aon_clk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/aon_osc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/gfr_clk_mux2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/io_clk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/io_osc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/rng.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/sys_clk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/sys_osc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/usb_clk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/usb_osc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_top_specific_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_arb.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_erase.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_info_cfg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_lcmgr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_prim_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_prog.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_rd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_region_cfg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_mp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_mp_data_region_sel.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_core.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_erase.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_prog.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd_buf_dep.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd_buffers.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_scramble.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/flash_ctrl/rtl/flash_ctrl_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_top_specific_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_cfg_en.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_ctrl.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_data_en_state.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_err.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_input_checks.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_kmac_if.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_op_state_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_reseed_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_sideload_key.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/keymgr/rtl/keymgr_sideload_key_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/keccak_2share.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/keccak_round.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_app.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_core.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_entropy.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_errchk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_msgfifo.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_reduced.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/kmac_staterd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/sha3.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/sha3_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/kmac/rtl/sha3pad.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_dmi_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_fsm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_kmac_if.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_regs_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_signal_decode.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_state_decode.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_state_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/lc_ctrl/rtl/lc_ctrl_state_transition.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/otp_macro/rtl/otp_macro.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/otp_macro/rtl/otp_macro_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/otp_macro/rtl/otp_macro_prim_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/otp_macro/rtl/otp_macro_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_core_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_dai.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_ecc_reg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_kdi.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lci.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_macro_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_buf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_scrmbl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_top_specific_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_alert_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_alert_receiver.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_alert_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_alert_to_diff.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_arbiter_fixed.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_arbiter_ppc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_arbiter_tree.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_arbiter_tree_dup.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ascon_duplex.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ascon_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ascon_round.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ascon_sbox.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_assert.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_blanker.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_cdc_rand_delay.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_cipher_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_clock_gating_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_clock_meas.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_clock_timeout.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_count.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_count_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_crc32.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_diff_decode.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_diff_encode.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_diff_to_alert.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_dom_and_2share.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_double_lfsr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_edge_detector.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_edn_req.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_esc_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_esc_receiver.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_esc_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_fifo_async.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_fifo_async_simple.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_fifo_async_sram_adapter.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_fifo_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_fifo_sync_cnt.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_filter.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_filter_ctr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_flop_macros.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_gate_gen.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_gf_mult.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_intr_hw.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_keccak.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_lc_and_hardened.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_lc_combine.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_lc_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_lc_or_hardened.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_lc_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_lc_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_leading_one_ppc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_lfsr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_max_tree.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_msb_extend.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi12_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi12_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi12_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi16_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi16_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi16_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi20_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi20_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi20_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi24_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi24_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi24_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi28_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi28_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi28_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi32_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi32_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi32_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi4_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi4_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi4_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi8_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi8_sender.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi8_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_mubi_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_multibit_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_onehot_check.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_onehot_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_onehot_mux.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_packer.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_packer_fifo.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_pad_wrapper_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_present.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_prince.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_pulse_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_racl_error_arb.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ram_1p_adv.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ram_1p_scr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ram_1r1w_adv.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ram_1r1w_async_adv.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ram_2p_adv.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_ram_2p_async_adv.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_reg_cdc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_reg_cdc_arb.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_reg_we_check.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_rom_adv.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_rst_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sec_anchor_buf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sec_anchor_flop.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_22_16_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_22_16_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_28_22_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_28_22_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_39_32_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_39_32_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_64_57_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_64_57_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_72_64_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_72_64_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_hamming_22_16_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_hamming_22_16_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_hamming_39_32_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_hamming_39_32_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_hamming_72_64_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_hamming_72_64_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_hamming_76_68_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_hamming_76_68_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_22_16_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_22_16_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_28_22_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_28_22_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_39_32_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_39_32_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_64_57_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_64_57_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_72_64_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_72_64_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_hamming_22_16_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_hamming_39_32_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_hamming_72_64_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inv_hamming_76_68_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_accu.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_class.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_esc_timer.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_lpg_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_ping_timer.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/alert_handler/rtl/alert_handler_reg_wrap.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sha2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sha2_32.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sha2_pad.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sha2_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_slicer.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sparse_fsm_flop.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sram_arbiter.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_subreg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_subreg_arb.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_subreg_ext.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_subreg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_subreg_shadow.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_subst_perm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sum_tree.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sync_reqack.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sync_reqack_data.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_sync_slow_fast.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_trivium.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_trivium_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_util_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_xoshiro256pp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_reg_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_cipher_control.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_cipher_control_fsm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_cipher_control_fsm_n.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_cipher_control_fsm_p.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_cipher_core.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_control.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_control_fsm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_control_fsm_n.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_control_fsm_p.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_core.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_ctr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_ctr_fsm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_ctr_fsm_n.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_ctr_fsm_p.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_ctrl_reg_shadowed.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_key_expand.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_mix_columns.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_mix_single_column.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_prng_clearing.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_prng_masking.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_reduced_round.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_reg_status.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_reg_top.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sbox.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sbox_canright.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sbox_canright_masked.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sbox_canright_masked_noreuse.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sbox_canright_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sbox_dom.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sbox_lut.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sel_buf_chk.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_shift_rows.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_sub_bytes.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/aes/rtl/aes_wrap.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_block_encrypt.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_cmd_stage.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_core.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_ctr_drbg_cmd.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_ctr_drbg_gen.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_ctr_drbg_upd.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_main_sm.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_reg_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_reg_top.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/csrng/rtl/csrng_state_db.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_and2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_buf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_clock_buf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_clock_div.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_clock_gating.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_clock_inv.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_clock_mux2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_flash.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_flop.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_flop_2sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_flop_en.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_flop_no_rst.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_generic_flash_bank.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_pad_attr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_pad_wrapper.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_1p.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_1r1w.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_2p.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_2p_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_rom.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_rom_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_usb_diff_rx.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_xnor2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_xor2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_1p_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_1r1w.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_2p.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_ram_2p_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_rom.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_rom_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_usb_diff_rx.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_xnor2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim_generic/rtl/prim_xor2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_compare.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_counter.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_mux.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_regs_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_scrambled_rom.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_compare.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_counter.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_fsm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_mux.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_regs_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_rom_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rom_ctrl/rtl/rom_ctrl_scrambled_rom.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/jtag_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_dbg_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_dmi_gate.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_mem_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_regs_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/sram2tlul.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_dmi.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_host.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_racl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_reg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_sram.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_assert.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_assert_multiple.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_data_integ_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_data_integ_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_err.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_err_resp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_fifo_async.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_fifo_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_jtag_dtm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_lc_gate.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_request_loopback.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_socket_1n.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_socket_m1.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_sram_byte.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_dmi.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_host.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_racl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_reg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_reg_racl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_sram.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_adapter_sram_racl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_assert.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_assert_multiple.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_cmd_intg_chk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_cmd_intg_gen.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_data_integ_dec.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_data_integ_enc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_err.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_err_resp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_fifo_async.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_fifo_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_jtag_dtm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_lc_gate.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_request_loopback.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_rsp_intg_chk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_rsp_intg_gen.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_socket_1n.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_socket_m1.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/tlul_sram_byte.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_ack_sm.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_ack_sm_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_adaptp_ht.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_bucket_ht.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_cntr_reg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_core.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_enable_delay.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_field_en.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_main_sm.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_main_sm_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_markov_ht.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_reg_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_reg_top.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_repcnt_ht.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_repcnts_ht.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/entropy_src/rtl/entropy_src_watermark_reg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/edn/rtl/edn.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/edn/rtl/edn_ack_sm.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/edn/rtl/edn_core.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/edn/rtl/edn_field_en.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/edn/rtl/edn_main_sm.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/edn/rtl/edn_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/edn/rtl/edn_reg_pkg.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/edn/rtl/edn_reg_top.sv  
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_byp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_clk_status.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_meas_chk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_root_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/clkmgr/rtl/clkmgr_trans.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_alert.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_bhv_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_dft.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_pulse_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/adc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/adc_ana.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_core.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_rx.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_tx.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/adc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/adc_ana.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/aon_clk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/aon_osc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_alert.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_bhv_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_clks_byp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_dft.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_entropy.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_pulse_sync.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/dev_entropy.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/gfr_clk_mux2.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/io_clk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/io_osc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/rng.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/sys_clk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/sys_osc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/usb_clk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/usb_osc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/vcmain_pgd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/vio_pgd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/ast_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/rglts_pdm_3p3v.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/vcaon_pgd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/vcc_pgd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/vcmain_pgd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip/ast/rtl/vio_pgd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_arb.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_core_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_erase.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_info_cfg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_lcmgr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_mem_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_prim_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_prog.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_rd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_ctrl_region_cfg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_mp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_mp_data_region_sel.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_core.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_erase.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_prog.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd_buf_dep.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_rd_buffers.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/flash_ctrl/rtl/flash_phy_scramble.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_core_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_dai.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_ecc_reg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_kdi.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lci.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_lfsr_timer.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_macro_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_buf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_part_unbuf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_scrmbl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_token_const.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/otp_ctrl/rtl/otp_ctrl_top_specific_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_cdc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_cdc_pulse.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_fsm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_slow_fsm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pwrmgr/rtl/pwrmgr_wake_info.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_cnsty_chk.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_crash_info.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_ctrl.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_leaf_rst.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_por.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rstmgr/rtl/rstmgr_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_gateway.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/rv_plic/rtl/rv_plic_target.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_alu.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_branch_predict.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_compressed_decoder.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_controller.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_core.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_counter.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_cs_registers.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_csr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_decoder.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_dummy_instr.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_ex_block.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_fetch_fifo.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_icache.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_id_stage.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_if_stage.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_load_store_unit.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_lockstep.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_multdiv_fast.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_multdiv_slow.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_pmp.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_prefetch_buffer.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_register_file_ff.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_register_file_fpga.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_register_file_latch.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_top_tracing.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_tracer.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_tracer_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/lowrisc_ibex/rtl/ibex_wb_stage.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_core_ibex/rtl/rv_core_ibex_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dm_csrs.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dm_mem.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dm_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dm_sba.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dm_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dmi_bscane_tap.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dmi_cdc.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dmi_intf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dmi_jtag.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dmi_jtag_tap.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/vendor/pulp_riscv_dbg/src/dmi_test.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/otp_ctrl/rtl/otp_ctrl_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_jtag_breakout.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_jtag_buf.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_strap_sampling.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/top_earlgrey/ip_autogen/pinmux/rtl/pinmux_wkup.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/RVVI/source/host/rvvi/rvviApiPkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/RVVI/source/host/rvvi/rvviTrace.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/bazel-out/k8-fastbuild/bin/hdl/chisel/src/soc/CoralNPUChiselSubsystem.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/console60k/src/gowin_pll/gowin_pll.v 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/console60k/src/gowin_pll/gowin_pll_mod.v 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/console60k/src/pll_init.v 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/ip/coralnpu_tlul/coralnpu_tlul_pkg_128.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/ip/coralnpu_tlul/coralnpu_tlul_pkg_32.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/dv/sv/dv_utils/dv_fcov_macros.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/dv/sv/dv_utils/dv_macros.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_assert_dummy_macros.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_assert_sec_cm.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_assert_standard_macros.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_assert_yosys_macros.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_fifo_assert.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_macros.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_secded_inc.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_util_get_scramble_params.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/tlul/rtl/sram2tlul.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/prim/rtl/prim_util_memload.svh 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/ip/sram/Sram.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/rtl/top_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/rtl/top_racl_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_core.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_rx.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/uart/rtl/uart_tx.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/jtag_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_dbg_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_dmi_gate.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_mem_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_reg_pkg.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/external/lowrisc_opentitan_gh/hw/ip/rv_dm/rtl/rv_dm_regs_reg_top.sv 
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/rtl/coralnpu_soc.sv
add_file C:/Workspace/FPGA/coralnpu-nano20k/bazel/bazel-out/k8-fastbuild/bin/hdl/chisel/src/coralnpu/CoreMiniAxi.sv
add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/rtl/chip_console60k_CoreMini.sv

add_file C:/Workspace/FPGA/coralnpu-nano20k/fpga/console60k/console60k.cst
set_option -top_module $top_name

# --- SYNTHESIS OPTIONS --------------------------------------
set_option -verilog_std sysv2017
set_option -global_freq 27
set_option -print_all_synthesis_warning 1

# --- PLACE & ROUTE OPTIONS ----------------------------------
set_option -timing_driven 1
set_option -gen_sdf 1
set_option -gen_verilog_sim_netlist 1
set_option -gen_text_timing_rpt 1
set_option -gen_io_cst 1
set_option -show_all_warn 1

# --- RUN FLOWS ----------------------------------------------
run all
# Alternatively:
#run syn
#run pnr

# --- SAVE SCRIPT SNAPSHOT -----------------------------------
saveto -all_options build_tcl__snapshot.tcl

# --- CLOSE PROJECT ------------------------------------------
run close